server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/LakDerana}
    data-username: ${DB_USER:postgres}
    data-password: ${DB_PASSWORD:password}

    # Connection Pool Settings
    hikari:
      pool-name: lakderana-hikari
      maximum-pool-size: 5
      minimum-idle: 3
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 300000

  # JPA Settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: "LAKDERANA_BASE"
        temp:
          use_jdbc_metadata_defaults: false
        proc:
          param_null_passing: true
      org:
        hibernate:
          envers:
            default_schema: "AUDIT"
            store_data_at_delete: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  security:
    signing-key: 8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2
    encoding-strength: 256
    security-realm: LakDerana-Web
    jwt:
      client-id: lakderanaweb
      client-secret: 8x/A?D(G+KbPeSgVkYp3s6v9y$B&E)H@McQfTjWmZq4t7w!z%C*F-JaNdRgUkXp2
      grant-type: password
      scope-read: read
      scope-write: write
      resource-ids: LakDerana-WebResource

auth:
  provider: ${AUTH_PROVIDER:surecore}